---
- name: Fact Variables
  hosts: all
  
  tasks:
  - name: Ver variables FACT
    debug:
      msg: "Architecture {{ansible_facts.architecture}} {{ansible_facts['bios_vendor']}} {{ansible_facts['all_ipv4_addresses'][0]}} "